account/urls.py
from django.urls import path
from . import views
from account.views import ChangePasswordView


app_name = 'account'

urlpatterns = [
    path('register/', views.register_account, name='signupuser'),
    path('login/', views.login_account, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('profile/', views.profileuser, name='profileuser'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

djstart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:

    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += (
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

homeapp/urls.py
from django.urls import path
from . import views

app_name = 'homeapp'

urlpatterns = [
    path('', views.home, name='homepage'),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User



class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

account/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from django.contrib import messages

from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin



def register_account(request):
    if request.method == 'GET':
        return render(request, 'account/register_account.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:

                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('account:profileuser')
            except IntegrityError:
                return render(request, 'account/register_account.html',
                              {'form': UserCreationForm(), 'error': 'User already exists'})
        else:
            return render(request, 'account/register_account.html',
                          {'form': UserCreationForm(), 'error': 'Passwords do not match'})



def login_account(request):
    if request.method == 'GET':
        return render(request, 'account/login.html', {'form': AuthenticationForm()})
    else:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is None:
            return render(request, 'account/login.html',
                          {'form': AuthenticationForm(),
                           'error': 'User or password not defined. Register'})
        else:
            login(request, user)
            return redirect('account:profileuser')


@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('homeapp:homepage')


 
@login_required
def profileuser(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('account:profileuser')
        else:
            return render(request, 'account/profileuser.html', {'profile_form': profile_form})    
    else:
        profile_form = ProfileForm()
        return render(request, 'account/profileuser.html', {'profile_form': profile_form})


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'account/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('account:profileuser')        

homeapp/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'homeapp/home.html')

homeapp/templates/homeapp/home.html
{% extends 'base.html' %}
{% block title %}
Homepage
{% endblock title %}
{% block content %}
<img src="https://images.unsplash.com/photo-1523800503107-5bc3ba2a6f81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80" style='width:100%;'>
{% endblock content %}

templates/_inc/_footer.html
<footer class="py-5">
<div class="container">
  <h3 class="text-center">&#169; TitleCompany, 2022</h3>
</div> 
</footer>

templates/_inc/_header.html
<header class="py-5">
  <div class="container">
    <h1 class="text-center">Boilerplate for django projects</h1>
  </div>
  <div class="container d-flex justify-content-center">
    {% if user.is_authenticated %}
    <div class="m-2"><h5>Hello {{ user.username }}</h5></div>
    <form action="{% url 'account:logoutuser' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-info">Exit</button>
    </form>
    {% endif %}
  </div>
</header>

templates/_inc/_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homeapp:homepage' %}">Home</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <ul class="navbar-nav d-flex">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'account:profileuser' %}"
            >Profile</a
          >
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'admin:index' %}"
            >Admin</a
          >
        </li>
        {% endif %}
      </ul>
      {% else %}
      <ul class="navbar-nav d-flex">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'account:signupuser' %}"
            >Sign Up</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'account:loginuser' %}"
            >Log in</a
          >
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'homeapp/app.css' %}">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>
<body>
{% include '_inc/_header.html' %}
{% include '_inc/_menu.html' %}

{% block content %}

{% endblock content %}
{% include '_inc/_footer.html' %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <script src="{% static 'homeapp/app.js' %}"></script>
</body>
</html>